name: beremiz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pyserial
  - matplotlib=3.5.3
  - lxml=4.9.1
  - click
  - wxpython=4.2.1
  - pyro5=5.14
  - pypubsub=4.0.3
  - jinja2=3.1.2
  - platformio=6.1.6
  - clang
  - clangxx
