#!/bin/bash -e

CONDA_DIR="${PWD}/conda"
PATH="${CONDA_DIR}/bin:$PATH"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

ARCH="MacOSX"
if [ `uname` = "Linux" ]; then
    ARCH="Linux"
fi
CONDA_URL=http://repo.continuum.io/miniconda/Miniconda3-latest-${ARCH}-x86_64.sh

function error {
    popd
    rm -rf ${CONDA_DIR}
    exit 1
}

if [ ! -d "$CONDA_DIR" ]; then
    mkdir -p ${CONDA_DIR}
    pushd ${CONDA_DIR}
    curl -L ${CONDA_URL} -o miniconda.sh || error
    bash miniconda.sh -f -b -p "${CONDA_DIR}" || error
    conda update --all -y || error
    conda config --set auto_update_conda False || error
    rm miniconda.sh

    conda env create -n beremiz --file $SCRIPT_DIR/conda.yaml || error

    popd
fi
